export type Slide = { id: string; chapter: string; title: string; subtitle?: string; type?: string; notes: string; data?: any };

export const slides: Slide[] = [
{ id:'title', chapter:'Why this matters', title:'I Still Call Myself a Designer', subtitle:'How design can help us build better public services', notes:'Opening frame.' },
{ id:'provocation', chapter:'Why this matters', title:'Sometimes a service works only because the user works hard.', subtitle:'A service is not well designed just because someone eventually gets through it.', notes:'Set the problem emotionally.' },
{ id:'pollbreak', chapter:'Why this matters', title:'Where do public services most often break down?', subtitle:'Let’s surface where friction shows up most for this room.', type:'text', notes:'Live poll interaction slide.' },
{ id:'insideout', chapter:'Why this matters', title:'How services fail from the inside out', subtitle:'Most service friction is not dramatic. It shows up as uncertainty, repetition, invisible handoffs and unclear next steps.', type:'bullets', notes:'Interpret poll.', data:{bullets:['people do not know where to start','language reflects our structure, not their task','the same information gets asked for more than once','digital tools sit on top of confusing processes','nobody owns the whole experience'], closing:'The user experiences the gaps between teams.'}},
{ id:'gov', chapter:'Why this matters', title:'Why this matters in government', subtitle:'Public services are shaped by legislation, equity, risk, trust, legacy systems and multiple teams, which makes design harder and more necessary.', type:'bullets', notes:'Civic relevance.', data:{bullets:['legislation matters','equity matters','trust matters','constraints are real','systems are layered','no one team owns the whole journey'], closing:'That is exactly why design matters here.'}},
{ id:'cos', chapter:'Why this matters', title:'Why this matters at City of Sydney', subtitle:'Many of our services are important, high-friction and emotionally loaded. Small failures in clarity can become big frustrations for the people using them and the staff delivering them.', type:'bullets', notes:'Local relevance.', data:{bullets:['our services are consequential','many journeys are high-friction','people often arrive uncertain','staff also feel the complexity','better design can reduce rework and avoidable contact','clarity is part of public trust'], closing:'People do not experience us as divisions. They experience us as moments.'}},
{ id:'who', chapter:'The lens', title:'Who I am', subtitle:'I did not come through one neat professional lane. I moved across different kinds of design and kept asking the same question: how do people actually experience systems?', type:'timeline', notes:'Short strategic biography.', data:{items:['creative and visual design roots','facilitation and strategy work','organisational and change design','systems and service thinking','public sector work','City of Sydney']}},
{ id:'constellation', chapter:'The lens', title:'Designer', subtitle:'Not because I do one kind of design, but because design is still the best word I have for how I work.', type:'constellation', notes:'Educational identity map.', data:{items:[['service','shaping the end-to-end experience'],['organisational','improving roles, rhythms and decision-making'],['change','helping people move through transition'],['experience','designing how systems feel to use'],['systems','seeing connections across teams, tools and policies'],['visual / graphic','making complex ideas clearer and more usable'],['technology','prototyping tools and new possibilities'],['facilitation / strategy','helping groups make sense, decide and move']] }},
{ id:'means', chapter:'The lens', title:'Design is not decoration. It is how we make intentions usable.', subtitle:'Good intentions, policy intent and service intent only matter if people can actually understand and move through what we create.', type:'bullets', notes:'Design principles.', data:{bullets:['make the next step visible','reduce unnecessary effort','connect the whole journey','design for real behaviour, not ideal behaviour','turn complexity into clarity','make systems feel more human'], closing:'Design sits between intention and lived experience.'}},
{ id:'servicedesign', chapter:'The lens', title:'Service design = shaping the whole experience', subtitle:'It looks at how people, process, policy, content, technology and decision-making work together across a full journey.', type:'layers', notes:'Whole-service framing.', data:{layers:['people','process','policy','content','data','digital','roles','environment','decisions','handoffs'], footer:'Not one touchpoint. Not one team. Not one channel. The whole service.'}},
{ id:'history', chapter:'The lens', title:'A compressed design lineage', subtitle:'As the problems got bigger, design expanded from products to experiences, then to services and public systems.', type:'progression', notes:'Functional lineage.', data:{items:['Product design → how things work, feel and are used','Human-centred design → start with people’s needs, not just organisational assumptions','Service design → design the end-to-end journey across channels and touchpoints','Public design → work across policy, operations, trust, equity and delivery in real civic systems'],footer:'The questions got bigger because the systems got bigger.'}},
{ id:'diamond', chapter:'The method', title:'Don’t rush to solve the wrong problem', subtitle:'The Double Diamond is a simple design model that helps teams understand before they narrow, explore before they commit and test before they lock things in.', type:'diamond', notes:'Anchor method.', data:{stages:[{name:'Discover',question:'What is really happening?',explanation:'Look beyond assumptions.',risk:'Skipping this stage solves symptoms.'},{name:'Define',question:'What is the right problem to solve?',explanation:'Turn observations into a clear challenge.',risk:'You frame the wrong target.'},{name:'Develop',question:'What are some possible responses?',explanation:'Generate and test options.',risk:'You choose first idea, not best idea.'},{name:'Deliver',question:'What should we implement and improve?',explanation:'Build, learn and refine.',risk:'You lock in too early.'}], caution:'Skipping the early stages often means solving the symptom instead of the cause.'}},
{ id:'worked', chapter:'The method', title:'Worked example of the method', subtitle:'A compact City of Sydney example of Discover → Define → Develop → Deliver in action.', type:'progression', notes:'Bridge theory to practice.', data:{items:['Discover → what we noticed','Define → what challenge we framed','Develop → what options we explored','Deliver → what we tested or changed'],footer:'The value is not speed alone. It is better framing before decisions.'}},
{ id:'practiceNow', chapter:'The method', title:'What this looks like in practice', subtitle:'My current work sits at the intersection of service design, change and practical delivery, helping improve how people move through services and how teams deliver them.', type:'cards', notes:'Current work themes.', data:{cards:['Making the front door clearer — improve entry pathways and intent routing.','Improving journeys, not just touchpoints — reduce dead ends across handoffs.','Connecting people, process and platform — align operations with digital experience.']}},
{ id:'case1', chapter:'The practice', title:'Case study: clarifying the front door', subtitle:'A design move: make entry choices clearer so people can start with confidence.', type:'beforeAfter', notes:'Case lesson.'},
{ id:'case2', chapter:'The practice', title:'Case study: staff experience is service design too', subtitle:'Internal friction shapes external experience; improving one improves the other.', type:'text', notes:'Distinct second lesson.'},
{ id:'workshopintro', chapter:'The practice', title:'A 12-minute introduction to service redesign', subtitle:'In pairs, you will use a compressed human-centred design process to reframe one frustrating service experience and sketch one better version.', type:'text', notes:'Workshop entry.'},
{ id:'workshopsteps', chapter:'The practice', title:'Design sprint in five steps', subtitle:'Interview 3m · Frame 2m · Ideate 3m · Sketch 2m · Test 2m', type:'steps', notes:'Instructional facilitation slide.', data:{steps:['Interview (3 mins): Ask your partner about a frustrating service experience. Listen for task, friction, feeling and need.','Frame (2 mins): Turn what you heard into one clear “How might we…” question.','Ideate (3 mins): Generate at least 6 ideas before picking one.','Sketch (2 mins): Draw or outline one better version of the experience.','Test (2 mins): Show it back to your partner and refine the idea.'], closing:'The goal is not to solve everything. It is to practice seeing and shaping a service differently.'}},
{ id:'workshopqr', chapter:'The practice', title:'Workshop QR companion', subtitle:'Scan to run the same five-step sequence on mobile and optionally share your output to the room.', type:'text', notes:'QR companion.'},
{ id:'takeaway', chapter:'The practice', title:'You do not need “designer” in your title to work like one', subtitle:'Many of the habits that improve services are available to anyone: paying attention, reframing clearly, making the next step visible and testing ideas before locking them in.', type:'bullets', notes:'Takeaways.', data:{bullets:['get closer to real user experience','define the problem before solutions','make the next step visible','reduce unnecessary effort','prototype early','improve across boundaries'], closing:'Design is not a department. It is a practice.'}},
{ id:'close', chapter:'The practice', title:'Better public services are not built by accident. They are designed.', subtitle:'And that work belongs to more of us than we think.', type:'text', notes:'Close.', data:{closing:'Every clearer step, better handoff and more legible journey changes how an institution feels to move through.'}}
];
