export type Slide = { id: string; title: string; subtitle?: string; type?: string; notes: string; data?: any };

export const slides: Slide[] = [
{id:'title',title:'I Still Call Myself a Designer',subtitle:'How design can help us build better public services',notes:'Open with personal framing and why this matters now.'},
{id:'provocation',title:'Sometimes a service works only because the user works hard.',subtitle:'Persistence is not the same thing as good design.',notes:'Set provocative premise.'},
{id:'who',title:'Who I am',type:'timeline',notes:'Walk through path from design craft to public service systems.',data:{items:['Design foundations','Facilitation practice','Systems thinking','Organisational design','Public service delivery']}},
{id:'constellation',title:'I still call myself a designer',type:'constellation',notes:'Identity is plural; design disciplines overlap.',data:{items:[['service','Designing end-to-end journeys.'],['product','Shaping useful digital tools.'],['organisational','Designing how teams work together.'],['change','Helping people adopt new ways of working.'],['experience','Making interactions coherent.'],['systems','Seeing patterns and dependencies.'],['graphic','Crafting clarity through visual hierarchy.'],['illustration','Explaining the abstract with imagery.'],['facilitation','Making collaborative progress possible.'],['strategy','Choosing where to focus.'],['technology','Understanding platform constraints and opportunities.']] }},
{id:'means',title:'Design is not decoration. It is how we make intentions usable.',type:'bullets',notes:'Define design values.',data:{bullets:['make the next step visible','reduce unnecessary effort','connect the whole journey','design for real behaviour','turn complexity into clarity','make systems feel more human']}},
{id:'insideout',title:'Public services often fail in ordinary ways',type:'toggle',notes:'Contrast internal logic with lived experience.',data:{inside:['teams','policy','systems','handoffs'],outside:['confusion','delay','repeated effort','invisible ownership'],closing:'The user experiences the gaps between teams.'}},
{id:'servicedesign',title:'Service design = shaping the whole experience',subtitle:'Not one touchpoint. The whole journey.',type:'layers',notes:'Service design spans layers.',data:{layers:['people','process','policy','content','data','digital','roles','environment','decisions','handoffs']}},
{id:'history',title:'A compressed design lineage',type:'progression',notes:'Show expansion of design scope.',data:{items:['Product design','Human-centred design','Service design','Public design'],footer:'The questions got bigger because the systems got bigger.'}},
{id:'diamond',title:'Don’t rush to solve the wrong problem',type:'diamond',notes:'Show method and risks.',data:{stages:[{name:'Discover',question:'What is happening now?',explanation:'Observe reality, not assumptions.',risk:'You solve symptoms.'},{name:'Define',question:'What problem matters most?',explanation:'Frame the challenge precisely.',risk:'You optimise the wrong target.'},{name:'Develop',question:'What could work better?',explanation:'Generate and test options.',risk:'You default to familiar ideas.'},{name:'Deliver',question:'How do we make it real?',explanation:'Implement with feedback loops.',risk:'You launch and lose learning.'}]}},
{id:'gov',title:'Government is where service design gets real',type:'bullets',notes:'Why civic context matters.',data:{bullets:['legislation matters','equity matters','trust matters','constraints are real','systems are layered','no one team owns the whole journey'],closing:'That is exactly why design matters here.'}},
{id:'cos',title:'Why this matters here',type:'bullets',notes:'Localise to City of Sydney.',data:{bullets:['our services are consequential','many journeys are high-friction','people arrive uncertain','staff also feel the complexity','better design can reduce rework, confusion and avoidable contact','clarity is part of public trust'],closing:'People do not experience us as divisions. They experience us as moments.'}},
{id:'doing',title:'What I’m doing now',type:'cards',notes:'Current priorities.',data:{cards:['Making the front door clearer','Improving journeys, not just touchpoints','Connecting people, process and platform']}},
{id:'case1',title:'Case study: clarifying the front door',type:'beforeAfter',notes:'Use slider to compare states.'},
{id:'case2',title:'Case study: designing across the journey',type:'text',notes:'Focus on handoffs and continuity.',subtitle:'Fewer dead ends. Clear ownership at transitions.'},
{id:'case3',title:'Case study: staff experience is service design too',type:'text',notes:'Internal friction creates external friction.',subtitle:'When staff navigate complexity, residents feel delay.'},
{id:'onepage',title:'Good service design in one page',type:'table',notes:'Inside-out vs designed-for-use patterns.'},
{id:'workshopintro',title:'Mini workshop: redesign one frustrating service experience',type:'steps',notes:'Set workshop cadence.',data:{steps:['pick one service or internal experience','describe what the person is trying to do','identify what gets in the way','turn it into a “How might we…” question','sketch one better version']}},
{id:'workshopsteps',title:'Workshop steps',type:'process',notes:'Group sequence.',data:{items:['Notice','Define','Ideate','Sketch','Share']}},
{id:'takeaway',title:'You do not need to have ‘designer’ in your title to work like one',type:'bullets',notes:'Reinforce practical takeaways.',data:{bullets:['get closer to real user experience','define the problem before solutions','make the next step visible','reduce unnecessary effort','prototype early','improve across boundaries']}},
{id:'close',title:'Better public services are not built by accident. They are designed.',subtitle:'And that work belongs to more of us than we think.',notes:'Close and invite action.'}
];
