export type Slide = { id: string; title: string; subtitle?: string; type?: string; notes: string; data?: any };

export const slides: Slide[] = [
{id:'title',title:'I Still Call Myself a Designer',subtitle:'Design helps us turn public intent into everyday clarity.',notes:'Open with personal framing and why this matters now.'},
{id:'provocation',title:'Sometimes a service works only because the user works hard.',subtitle:'If people must push through confusion, the service design is doing too little.',notes:'Set provocative premise.'},
{id:'who',title:'Who I am',subtitle:'A path from craft to systems to public impact.',type:'timeline',notes:'Walk through path from design craft to public service systems.',data:{items:['Design foundations','Facilitation practice','Systems thinking','Organisational design','Public service delivery']}},
{id:'constellation',title:'I still call myself a designer',subtitle:'“Designer” is the anchor; these are the connected practices I draw from.',type:'constellation',notes:'Identity is plural; design disciplines overlap.',data:{items:[['service','Shape whole journeys, not isolated touchpoints.'],['product','Make digital tools useful and trustworthy.'],['organisational','Design clearer ways teams coordinate.'],['change','Support adoption, not just delivery.'],['experience','Reduce friction across moments.'],['systems','Spot patterns and dependencies.'],['graphic','Make information legible at speed.'],['illustration','Explain complexity visually.'],['facilitation','Help groups make progress together.'],['strategy','Choose what matters most now.'],['technology','Work with constraints, not against them.']] }},
{id:'means',title:'Design is not decoration. It is how we make intentions usable.',subtitle:'Plainly: good design makes the next action obvious and effort proportionate.',type:'bullets',notes:'Define design values.',data:{bullets:['make the next step visible','reduce unnecessary effort','connect the whole journey','design for real behaviour','turn complexity into clarity','make systems feel more human']}},
{id:'insideout',title:'Public services often fail in ordinary ways',subtitle:'Inside logic can look tidy while lived experience feels fragmented.',type:'toggle',notes:'Contrast internal logic with lived experience.',data:{inside:['teams','policy','systems','handoffs'],outside:['confusion','delay','repeated effort','invisible ownership'],closing:'The user experiences the gaps between teams.'}},
{id:'servicedesign',title:'Service design = shaping the whole experience',subtitle:'It coordinates people, process, policy and platforms so journeys hold together.',type:'layers',notes:'Service design spans layers.',data:{layers:['people','process','policy','content','data','digital','roles','environment','decisions','handoffs']}},
{id:'history',title:'A compressed design lineage',subtitle:'The focus widened: from products, to people, to services, to systems in public life.',type:'progression',notes:'Show expansion of design scope.',data:{items:['Product design','Human-centred design','Service design','Public design'],footer:'The questions got bigger because the systems got bigger.'}},
{id:'diamond',title:'Don’t rush to solve the wrong problem',subtitle:'The Double Diamond slows us down at the right moments so delivery is smarter.',type:'diamond',notes:'Show method and risks.',data:{stages:[{name:'Discover',question:'What is happening now?',explanation:'Observe lived reality before deciding.',risk:'You solve symptoms.'},{name:'Define',question:'What problem matters most?',explanation:'Frame the challenge precisely.',risk:'You optimise the wrong target.'},{name:'Develop',question:'What could work better?',explanation:'Generate and test options.',risk:'You default to familiar ideas.'},{name:'Deliver',question:'How do we make it real?',explanation:'Implement and keep learning.',risk:'You launch and lose feedback.'}]}},
{id:'gov',title:'Government is where service design gets real',subtitle:'Public services must work for everyone, under real constraints, at real scale.',type:'bullets',notes:'Why civic context matters.',data:{bullets:['legislation matters','equity matters','trust matters','constraints are real','systems are layered','no one team owns the whole journey'],closing:'That is exactly why design matters here.'}},
{id:'cos',title:'Why this matters here',subtitle:'At City of Sydney, better service design means clearer moments for residents and staff.',type:'bullets',notes:'Localise to City of Sydney.',data:{bullets:['our services are consequential','many journeys are high-friction','people arrive uncertain','staff also feel the complexity','better design can reduce rework, confusion and avoidable contact','clarity is part of public trust'],closing:'People do not experience us as divisions. They experience us as moments.'}},
{id:'doing',title:'What I’m doing now',subtitle:'Three practical shifts that improve outcomes without adding noise.',type:'cards',notes:'Current priorities.',data:{cards:['Making the front door clearer','Improving journeys, not just touchpoints','Connecting people, process and platform']}},
{id:'case1',title:'Case study: clarifying the front door',subtitle:'Before: people guess. After: people can choose confidently.',type:'beforeAfter',notes:'Use slider to compare states.'},
{id:'case2',title:'Case study: designing across the journey',subtitle:'Good handoffs reduce dead-ends and duplicated effort.',type:'text',notes:'Focus on handoffs and continuity.'},
{id:'case3',title:'Case study: staff experience is service design too',subtitle:'Internal friction reliably becomes external friction.',type:'text',notes:'Internal friction creates external friction.'},
{id:'onepage',title:'Good service design in one page',subtitle:'A quick reference: inside-out operations vs designed-for-use experiences.',type:'table',notes:'Inside-out vs designed-for-use patterns.'},
{id:'workshopintro',title:'Mini workshop: redesign one frustrating service experience',subtitle:'Use this 5-step prompt to move from complaint to practical redesign.',type:'steps',notes:'Set workshop cadence.',data:{steps:['pick one service or internal experience','describe what the person is trying to do','identify what gets in the way','turn it into a “How might we…” question','sketch one better version']}},
{id:'workshopsteps',title:'Workshop steps',subtitle:'Notice what is happening. Define what matters. Then make it better together.',type:'process',notes:'Group sequence.',data:{items:['Notice','Define','Ideate','Sketch','Share']}},
{id:'takeaway',title:'You do not need to have “designer” in your title to work like one',subtitle:'Start with lived experience, name the real problem, and improve the next step.',type:'bullets',notes:'Reinforce practical takeaways.',data:{bullets:['get closer to real user experience','define the problem before solutions','make the next step visible','reduce unnecessary effort','prototype early','improve across boundaries']}},
{id:'close',title:'Better public services are not built by accident. They are designed.',subtitle:'And that work belongs to more of us than we think.',notes:'Close and invite action.'}
];
